#! /bin/zsh

# check existence of any commands to be installed
function is_existed() {
if ! command -v $1 &> /dev/null
then
    echo "$1 could not be found";
    return 1
else
    return 0
fi
}

function main() {
    echo "function test"
}


if [[ "${(%):-%N}" -eq 1]]; then
    main "$@"
fi
