#! /bin/zsh
echo "running install_macos" 
echo "eval \$(/opt/homebrew/bin/brew shellenv)" > ${HOME}/.zprofile
source ${HOME}/.zprofile

[ -z "$(which brew)" ] &&
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Updating homebrew"

brew install \
	fd ag ripgrep ant cmake cmus coreutils cscope exiftool doxygen liboauth \
	git graphviz imagemagick leiningen gnupg \
	ranger tree vim wget zsh nvim python highlight bat \
	reattach-to-user-namespace pinentry-mac bash-completion tmux gnuplot w3m yarn

